### ISSUE TITLE
You have no permisssion to change the NPC  spawnrate

### ISSUE THREAD

**Issue by Revenger** [Pryaxis/TShock#1913]
* TShock version: 4.4.0
* TShock build number (if known): Pre-release 8

#### Reproduction steps (if applicable)?

When logging into the server a message that you cant change the NPC spawnrate is shown to all players even super admins having the command.

#### Any screenshots?
![20200525154121_1](https://user-images.githubusercontent.com/597280/82790283-66816980-9e9e-11ea-9c8c-dde7794ee9c8.jpg)
![spawnrate](https://user-images.githubusercontent.com/597280/82790439-a34d6080-9e9e-11ea-97be-e6f90e104ff8.PNG)

I don't have spawnrate set for default users and they still get this message on world login when they shouldn't be seeing anything.

**Comment by hakusaro** [comment]
This is fixed in https://github.com/Pryaxis/TShock/commit/d1b27d8b7aa17cc33ab6a9e0e794878c43f5ba76 -- it's related to the client sending journey mode NPC spawn rate changes when it shouldn't. It has nothing to do with `/spawnrate` ;) but we've fixed it so it'll be gone in pre-release 9.

**Comment by pluto00987** [comment]
@hakusaro 
I'm still seeing this 'NPC spawn rate' permission error through Pre 11.

**Comment by hakusaro** [comment]
Likely a regression due to rewrite of NetModules handling code.

**Comment by kubedzero** [comment]
+1 was about to submit a new issue. I'm going to just paste what I had drafted:

_______


I'm seeing a permissions error pop up on each join of a Tshock instance. The error will say `You do not have permission to modify the NPC spawn rate of the server.` The Debug logs show `Bouncer / OnPlayerDebuff rejected from hostile/pvp from <name>`

I'm not sure if this is due to a character of a certain type (journey/classic/mediumcore/hardcore) influencing the spawn rate of the world, 

* TShock version: pre-11 and https://github.com/Pryaxis/TShock/pull/2020/checks?check_run_id=748092720 which is post-pre-11

#### Reproduction steps?

1. Run Tshock, make a new world (default), make a new character, log in
1. Note the error in the logs and in the Terraria UI 

#### Logs

```
2020-06-07 21:41:29 - TShock: INFO: test1 (10.1.1.21) from 'guest' group joined. (1/8)
2020-06-07 21:41:29 - Utils: INFO: Broadcast: test1 has joined.
2020-06-07 21:41:29 - TextLog: VERBOSE: Bouncer / OnPlayerBuff rejected hostile/pvp from test1
2020-06-07 21:41:29 - TextLog: VERBOSE: GetDataHandlers / HandlePlayerBuffList handled event and sent data test1
```

#### Any screenshots?

![2020-06-07 21_42_09-10 1 1 9 - Remote Desktop Connection](https://user-images.githubusercontent.com/51148401/83993671-f1377f00-a908-11ea-9cb7-1bce878f14c5.png)

**Comment by pluto00987** [comment]
This is noted as fixed in the Pre12 release notes.
I can confirm I no longer see the error on a Pre12 server.
