### ISSUE TITLE
TShock unsupported on Ubuntu 24.04

### ISSUE THREAD

**Issue by SakuraIsayeki** [Pryaxis/TShock#3100]
* TShock version: Release 5.2.4
* TShock build number (if known):

#### Context

When trying to launch TShock on an Ubuntu 24.04 server, the process fails, due to its dependency on .NET 6.0, an EOL version of the .NET framework.

#### Any stack traces or error messages (if known)?

Using Systemd: 
```
Started tshock.service - Terraria Server.
You must install or update .NET to run this application.
App: /home/sakura/tshock/TShock.Server
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/lib/dotnet
The following frameworks were found:
  8.0.15 at [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
Learn more:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=ubuntu.24.04-x64&os=ubuntu.24.04
tshock.service: Main process exited, code=exited, status=150/n/a
tshock.service: Failed with result 'exit-code'.
```

#### Workaround
Using the `./TShock.Installer` executable is possible to use a non-system provided framework. However, this leaves no place for correct automation and integration using the `./TShock.Launcher` executable.

Given PR #3050 was merged, consider releasing an intermediary version or pre-release ASAP, to allow for users affected by this to effectively mitigate dependencies issues.

**Comment by hakusaro** [comment]
Surely we did not need this issue

**Comment by SakuraIsayeki** [comment]
Fixed per https://github.com/Pryaxis/TShock/discussions/3101 release.

**Comment by changemewtf** [comment]
I was a bit confused because I was still getting this error on the beta, but then I saw this in the output for the Installer:

```
To be able to run TShock.Server yourself set the environment variable DOTNET_ROOT=/home/terraria/dotnet
```

That fixed me right up. Running like this works for me:

```sh
DOTNET_ROOT=/home/terraria/dotnet ./TShock.Server
```

**Comment by pacenadhif778** [comment]
> I was a bit confused because I was still getting this error on the beta, but then I saw this in the output for the Installer:
> 
> ```
> To be able to run TShock.Server yourself set the environment variable DOTNET_ROOT=/home/terraria/dotnet
> ```
> 
> That fixed me right up. Running like this works for me:
> 
> DOTNET_ROOT=/home/terraria/dotnet ./TShock.Server

changes to dotnet 9
